// Generated by Supabase MCP `generate_typescript_types` (project hccsqofkmqyldkenapqr).
// Do not edit by hand — regenerate after every migration.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.18"
  }
  public: {
    Tables: {
      appointment_events: {
        Row: {
          actor_type: Database["public"]["Enums"]["actor_type"]
          appointment_id: string
          changed_by: string | null
          channel: string
          clinic_id: string
          created_at: string
          from_status: Database["public"]["Enums"]["appointment_status"] | null
          id: number
          note: string | null
          to_status: Database["public"]["Enums"]["appointment_status"]
        }
        Insert: {
          actor_type: Database["public"]["Enums"]["actor_type"]
          appointment_id: string
          changed_by?: string | null
          channel: string
          clinic_id: string
          created_at?: string
          from_status?: Database["public"]["Enums"]["appointment_status"] | null
          id?: never
          note?: string | null
          to_status: Database["public"]["Enums"]["appointment_status"]
        }
        Update: {
          actor_type?: Database["public"]["Enums"]["actor_type"]
          appointment_id?: string
          changed_by?: string | null
          channel?: string
          clinic_id?: string
          created_at?: string
          from_status?: Database["public"]["Enums"]["appointment_status"] | null
          id?: never
          note?: string | null
          to_status?: Database["public"]["Enums"]["appointment_status"]
        }
        Relationships: [
          {
            foreignKeyName: "appointment_events_appointment_id_fkey"
            columns: ["appointment_id"]
            isOneToOne: false
            referencedRelation: "appointments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "appointment_events_changed_by_fkey"
            columns: ["changed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "appointment_events_clinic_id_fkey"
            columns: ["clinic_id"]
            isOneToOne: false
            referencedRelation: "clinics"
            referencedColumns: ["id"]
          },
        ]
      }
      appointments: {
        Row: {
          appointment_date: string
          clinic_id: string
          created_at: string
          created_by: string | null
          doctor_id: string
          ends_at: string
          external_ref: string | null
          id: string
          notes: string | null
          patient_id: string
          reason_for_visit: string | null
          source: Database["public"]["Enums"]["appointment_source"]
          starts_at: string
          status: Database["public"]["Enums"]["appointment_status"]
          token_number: number
          updated_at: string
        }
        Insert: {
          appointment_date: string
          clinic_id: string
          created_at?: string
          created_by?: string | null
          doctor_id: string
          ends_at: string
          external_ref?: string | null
          id?: string
          notes?: string | null
          patient_id: string
          reason_for_visit?: string | null
          source: Database["public"]["Enums"]["appointment_source"]
          starts_at: string
          status?: Database["public"]["Enums"]["appointment_status"]
          token_number: number
          updated_at?: string
        }
        Update: {
          appointment_date?: string
          clinic_id?: string
          created_at?: string
          created_by?: string | null
          doctor_id?: string
          ends_at?: string
          external_ref?: string | null
          id?: string
          notes?: string | null
          patient_id?: string
          reason_for_visit?: string | null
          source?: Database["public"]["Enums"]["appointment_source"]
          starts_at?: string
          status?: Database["public"]["Enums"]["appointment_status"]
          token_number?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "appointments_clinic_id_fkey"
            columns: ["clinic_id"]
            isOneToOne: false
            referencedRelation: "clinics"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "appointments_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "appointments_doctor_id_fkey"
            columns: ["doctor_id"]
            isOneToOne: false
            referencedRelation: "doctors"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "appointments_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: false
            referencedRelation: "patients"
            referencedColumns: ["id"]
          },
        ]
      }
      clinics: {
        Row: {
          address: string | null
          created_at: string
          id: string
          lab_requires_verification: boolean
          name: string
          phone: string | null
          timezone: string
        }
        Insert: {
          address?: string | null
          created_at?: string
          id?: string
          lab_requires_verification?: boolean
          name: string
          phone?: string | null
          timezone?: string
        }
        Update: {
          address?: string | null
          created_at?: string
          id?: string
          lab_requires_verification?: boolean
          name?: string
          phone?: string | null
          timezone?: string
        }
        Relationships: []
      }
      consultation_addenda: {
        Row: {
          author_id: string | null
          author_name: string
          clinic_id: string
          consultation_id: string
          created_at: string
          id: string
          text: string
        }
        Insert: {
          author_id?: string | null
          author_name: string
          clinic_id: string
          consultation_id: string
          created_at?: string
          id?: string
          text: string
        }
        Update: {
          author_id?: string | null
          author_name?: string
          clinic_id?: string
          consultation_id?: string
          created_at?: string
          id?: string
          text?: string
        }
        Relationships: [
          {
            foreignKeyName: "consultation_addenda_author_id_fkey"
            columns: ["author_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "consultation_addenda_clinic_id_fkey"
            columns: ["clinic_id"]
            isOneToOne: false
            referencedRelation: "clinics"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "consultation_addenda_consultation_id_fkey"
            columns: ["consultation_id"]
            isOneToOne: false
            referencedRelation: "consultations"
            referencedColumns: ["id"]
          },
        ]
      }
      consultations: {
        Row: {
          advice: string | null
          appointment_id: string
          chief_complaint: string | null
          clinic_id: string
          created_at: string
          created_by: string | null
          diagnosis: string | null
          doctor_id: string
          examination: string | null
          finalized_at: string | null
          follow_up_date: string | null
          history: string | null
          id: string
          notes: string | null
          patient_id: string
          status: Database["public"]["Enums"]["consultation_status"]
          updated_at: string
          vitals: Json
        }
        Insert: {
          advice?: string | null
          appointment_id: string
          chief_complaint?: string | null
          clinic_id: string
          created_at?: string
          created_by?: string | null
          diagnosis?: string | null
          doctor_id: string
          examination?: string | null
          finalized_at?: string | null
          follow_up_date?: string | null
          history?: string | null
          id?: string
          notes?: string | null
          patient_id: string
          status?: Database["public"]["Enums"]["consultation_status"]
          updated_at?: string
          vitals?: Json
        }
        Update: {
          advice?: string | null
          appointment_id?: string
          chief_complaint?: string | null
          clinic_id?: string
          created_at?: string
          created_by?: string | null
          diagnosis?: string | null
          doctor_id?: string
          examination?: string | null
          finalized_at?: string | null
          follow_up_date?: string | null
          history?: string | null
          id?: string
          notes?: string | null
          patient_id?: string
          status?: Database["public"]["Enums"]["consultation_status"]
          updated_at?: string
          vitals?: Json
        }
        Relationships: [
          {
            foreignKeyName: "consultations_appointment_id_fkey"
            columns: ["appointment_id"]
            isOneToOne: true
            referencedRelation: "appointments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "consultations_clinic_id_fkey"
            columns: ["clinic_id"]
            isOneToOne: false
            referencedRelation: "clinics"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "consultations_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "consultations_doctor_id_fkey"
            columns: ["doctor_id"]
            isOneToOne: false
            referencedRelation: "doctors"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "consultations_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: false
            referencedRelation: "patients"
            referencedColumns: ["id"]
          },
        ]
      }
      doctor_leaves: {
        Row: {
          clinic_id: string
          created_at: string
          doctor_id: string
          id: string
          leave_date: string
          reason: string | null
        }
        Insert: {
          clinic_id: string
          created_at?: string
          doctor_id: string
          id?: string
          leave_date: string
          reason?: string | null
        }
        Update: {
          clinic_id?: string
          created_at?: string
          doctor_id?: string
          id?: string
          leave_date?: string
          reason?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "doctor_leaves_clinic_id_fkey"
            columns: ["clinic_id"]
            isOneToOne: false
            referencedRelation: "clinics"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "doctor_leaves_doctor_id_fkey"
            columns: ["doctor_id"]
            isOneToOne: false
            referencedRelation: "doctors"
            referencedColumns: ["id"]
          },
        ]
      }
      doctor_schedules: {
        Row: {
          clinic_id: string
          created_at: string
          doctor_id: string
          end_time: string
          id: string
          start_time: string
          weekday: number
        }
        Insert: {
          clinic_id: string
          created_at?: string
          doctor_id: string
          end_time: string
          id?: string
          start_time: string
          weekday: number
        }
        Update: {
          clinic_id?: string
          created_at?: string
          doctor_id?: string
          end_time?: string
          id?: string
          start_time?: string
          weekday?: number
        }
        Relationships: [
          {
            foreignKeyName: "doctor_schedules_clinic_id_fkey"
            columns: ["clinic_id"]
            isOneToOne: false
            referencedRelation: "clinics"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "doctor_schedules_doctor_id_fkey"
            columns: ["doctor_id"]
            isOneToOne: false
            referencedRelation: "doctors"
            referencedColumns: ["id"]
          },
        ]
      }
      doctors: {
        Row: {
          clinic_id: string
          consultation_fee: number
          created_at: string
          default_slot_minutes: number
          full_name: string
          id: string
          is_active: boolean
          profile_id: string | null
          specialization: string
        }
        Insert: {
          clinic_id: string
          consultation_fee?: number
          created_at?: string
          default_slot_minutes?: number
          full_name: string
          id?: string
          is_active?: boolean
          profile_id?: string | null
          specialization: string
        }
        Update: {
          clinic_id?: string
          consultation_fee?: number
          created_at?: string
          default_slot_minutes?: number
          full_name?: string
          id?: string
          is_active?: boolean
          profile_id?: string | null
          specialization?: string
        }
        Relationships: [
          {
            foreignKeyName: "doctors_clinic_id_fkey"
            columns: ["clinic_id"]
            isOneToOne: false
            referencedRelation: "clinics"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "doctors_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      inbound_booking_requests: {
        Row: {
          appointment_id: string | null
          caller_phone: string | null
          channel: Database["public"]["Enums"]["inbound_channel"]
          clinic_id: string
          created_at: string
          error: string | null
          external_ref: string | null
          id: string
          parsed_patient_name: string | null
          raw_payload: Json
          requested_doctor_id: string | null
          requested_time: string | null
          status: Database["public"]["Enums"]["inbound_status"]
        }
        Insert: {
          appointment_id?: string | null
          caller_phone?: string | null
          channel: Database["public"]["Enums"]["inbound_channel"]
          clinic_id: string
          created_at?: string
          error?: string | null
          external_ref?: string | null
          id?: string
          parsed_patient_name?: string | null
          raw_payload: Json
          requested_doctor_id?: string | null
          requested_time?: string | null
          status?: Database["public"]["Enums"]["inbound_status"]
        }
        Update: {
          appointment_id?: string | null
          caller_phone?: string | null
          channel?: Database["public"]["Enums"]["inbound_channel"]
          clinic_id?: string
          created_at?: string
          error?: string | null
          external_ref?: string | null
          id?: string
          parsed_patient_name?: string | null
          raw_payload?: Json
          requested_doctor_id?: string | null
          requested_time?: string | null
          status?: Database["public"]["Enums"]["inbound_status"]
        }
        Relationships: [
          {
            foreignKeyName: "inbound_booking_requests_appointment_id_fkey"
            columns: ["appointment_id"]
            isOneToOne: false
            referencedRelation: "appointments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inbound_booking_requests_clinic_id_fkey"
            columns: ["clinic_id"]
            isOneToOne: false
            referencedRelation: "clinics"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inbound_booking_requests_requested_doctor_id_fkey"
            columns: ["requested_doctor_id"]
            isOneToOne: false
            referencedRelation: "doctors"
            referencedColumns: ["id"]
          },
        ]
      }
      ingestion_jobs: {
        Row: {
          attempts: number
          clinic_id: string
          created_at: string
          id: string
          last_error: string | null
          patient_id: string
          run_after: string
          source_id: string
          source_type: Database["public"]["Enums"]["record_source_type"]
          status: Database["public"]["Enums"]["job_status"]
          updated_at: string
        }
        Insert: {
          attempts?: number
          clinic_id: string
          created_at?: string
          id?: string
          last_error?: string | null
          patient_id: string
          run_after?: string
          source_id: string
          source_type: Database["public"]["Enums"]["record_source_type"]
          status?: Database["public"]["Enums"]["job_status"]
          updated_at?: string
        }
        Update: {
          attempts?: number
          clinic_id?: string
          created_at?: string
          id?: string
          last_error?: string | null
          patient_id?: string
          run_after?: string
          source_id?: string
          source_type?: Database["public"]["Enums"]["record_source_type"]
          status?: Database["public"]["Enums"]["job_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "ingestion_jobs_clinic_id_fkey"
            columns: ["clinic_id"]
            isOneToOne: false
            referencedRelation: "clinics"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ingestion_jobs_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: false
            referencedRelation: "patients"
            referencedColumns: ["id"]
          },
        ]
      }
      lab_critical_alerts: {
        Row: {
          acknowledged_at: string | null
          acknowledged_by: string | null
          clinic_id: string
          created_at: string
          doctor_id: string
          id: string
          note: string | null
          order_id: string
          patient_id: string
          result_id: string
        }
        Insert: {
          acknowledged_at?: string | null
          acknowledged_by?: string | null
          clinic_id: string
          created_at?: string
          doctor_id: string
          id?: string
          note?: string | null
          order_id: string
          patient_id: string
          result_id: string
        }
        Update: {
          acknowledged_at?: string | null
          acknowledged_by?: string | null
          clinic_id?: string
          created_at?: string
          doctor_id?: string
          id?: string
          note?: string | null
          order_id?: string
          patient_id?: string
          result_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "lab_critical_alerts_acknowledged_by_fkey"
            columns: ["acknowledged_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lab_critical_alerts_clinic_id_fkey"
            columns: ["clinic_id"]
            isOneToOne: false
            referencedRelation: "clinics"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lab_critical_alerts_doctor_id_fkey"
            columns: ["doctor_id"]
            isOneToOne: false
            referencedRelation: "doctors"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lab_critical_alerts_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "lab_orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lab_critical_alerts_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: false
            referencedRelation: "patients"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lab_critical_alerts_result_id_fkey"
            columns: ["result_id"]
            isOneToOne: true
            referencedRelation: "lab_results"
            referencedColumns: ["id"]
          },
        ]
      }
      lab_order_events: {
        Row: {
          actor_id: string | null
          clinic_id: string
          created_at: string
          event: string
          from_status: string | null
          id: number
          order_id: string
          order_item_id: string | null
          to_status: string | null
        }
        Insert: {
          actor_id?: string | null
          clinic_id: string
          created_at?: string
          event: string
          from_status?: string | null
          id?: never
          order_id: string
          order_item_id?: string | null
          to_status?: string | null
        }
        Update: {
          actor_id?: string | null
          clinic_id?: string
          created_at?: string
          event?: string
          from_status?: string | null
          id?: never
          order_id?: string
          order_item_id?: string | null
          to_status?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "lab_order_events_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lab_order_events_clinic_id_fkey"
            columns: ["clinic_id"]
            isOneToOne: false
            referencedRelation: "clinics"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lab_order_events_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "lab_orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lab_order_events_order_item_id_fkey"
            columns: ["order_item_id"]
            isOneToOne: false
            referencedRelation: "lab_order_items"
            referencedColumns: ["id"]
          },
        ]
      }
      lab_order_items: {
        Row: {
          cancelled_reason: string | null
          created_at: string
          entered_at: string | null
          entered_by: string | null
          id: string
          order_id: string
          rejection_reason: string | null
          released_at: string | null
          released_by: string | null
          return_comment: string | null
          sample_id: string | null
          sort_order: number
          status: Database["public"]["Enums"]["lab_item_status"]
          test_code: string
          test_id: string
          test_name: string
          updated_at: string
          verified_at: string | null
          verified_by: string | null
        }
        Insert: {
          cancelled_reason?: string | null
          created_at?: string
          entered_at?: string | null
          entered_by?: string | null
          id?: string
          order_id: string
          rejection_reason?: string | null
          released_at?: string | null
          released_by?: string | null
          return_comment?: string | null
          sample_id?: string | null
          sort_order?: number
          status?: Database["public"]["Enums"]["lab_item_status"]
          test_code: string
          test_id: string
          test_name: string
          updated_at?: string
          verified_at?: string | null
          verified_by?: string | null
        }
        Update: {
          cancelled_reason?: string | null
          created_at?: string
          entered_at?: string | null
          entered_by?: string | null
          id?: string
          order_id?: string
          rejection_reason?: string | null
          released_at?: string | null
          released_by?: string | null
          return_comment?: string | null
          sample_id?: string | null
          sort_order?: number
          status?: Database["public"]["Enums"]["lab_item_status"]
          test_code?: string
          test_id?: string
          test_name?: string
          updated_at?: string
          verified_at?: string | null
          verified_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "lab_order_items_entered_by_fkey"
            columns: ["entered_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lab_order_items_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "lab_orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lab_order_items_released_by_fkey"
            columns: ["released_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lab_order_items_sample_id_fkey"
            columns: ["sample_id"]
            isOneToOne: false
            referencedRelation: "lab_samples"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lab_order_items_test_id_fkey"
            columns: ["test_id"]
            isOneToOne: false
            referencedRelation: "lab_tests"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lab_order_items_verified_by_fkey"
            columns: ["verified_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      lab_orders: {
        Row: {
          appointment_id: string
          cancelled_reason: string | null
          clinic_id: string
          clinical_note: string | null
          consultation_id: string | null
          created_at: string
          created_by: string | null
          id: string
          order_number: string
          ordering_doctor_id: string
          patient_id: string
          priority: Database["public"]["Enums"]["lab_priority"]
          reviewed_at: string | null
          reviewed_by: string | null
          status: Database["public"]["Enums"]["lab_order_status"]
          updated_at: string
        }
        Insert: {
          appointment_id: string
          cancelled_reason?: string | null
          clinic_id: string
          clinical_note?: string | null
          consultation_id?: string | null
          created_at?: string
          created_by?: string | null
          id?: string
          order_number: string
          ordering_doctor_id: string
          patient_id: string
          priority?: Database["public"]["Enums"]["lab_priority"]
          reviewed_at?: string | null
          reviewed_by?: string | null
          status?: Database["public"]["Enums"]["lab_order_status"]
          updated_at?: string
        }
        Update: {
          appointment_id?: string
          cancelled_reason?: string | null
          clinic_id?: string
          clinical_note?: string | null
          consultation_id?: string | null
          created_at?: string
          created_by?: string | null
          id?: string
          order_number?: string
          ordering_doctor_id?: string
          patient_id?: string
          priority?: Database["public"]["Enums"]["lab_priority"]
          reviewed_at?: string | null
          reviewed_by?: string | null
          status?: Database["public"]["Enums"]["lab_order_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "lab_orders_appointment_id_fkey"
            columns: ["appointment_id"]
            isOneToOne: false
            referencedRelation: "appointments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lab_orders_clinic_id_fkey"
            columns: ["clinic_id"]
            isOneToOne: false
            referencedRelation: "clinics"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lab_orders_consultation_id_fkey"
            columns: ["consultation_id"]
            isOneToOne: false
            referencedRelation: "consultations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lab_orders_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lab_orders_ordering_doctor_id_fkey"
            columns: ["ordering_doctor_id"]
            isOneToOne: false
            referencedRelation: "doctors"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lab_orders_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: false
            referencedRelation: "patients"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lab_orders_reviewed_by_fkey"
            columns: ["reviewed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      lab_reference_ranges: {
        Row: {
          age_max_years: number | null
          age_min_years: number | null
          created_at: string
          critical_high: number | null
          critical_low: number | null
          high: number | null
          id: string
          low: number | null
          parameter_id: string
          sex: Database["public"]["Enums"]["lab_range_sex"]
          text_normal: string | null
        }
        Insert: {
          age_max_years?: number | null
          age_min_years?: number | null
          created_at?: string
          critical_high?: number | null
          critical_low?: number | null
          high?: number | null
          id?: string
          low?: number | null
          parameter_id: string
          sex?: Database["public"]["Enums"]["lab_range_sex"]
          text_normal?: string | null
        }
        Update: {
          age_max_years?: number | null
          age_min_years?: number | null
          created_at?: string
          critical_high?: number | null
          critical_low?: number | null
          high?: number | null
          id?: string
          low?: number | null
          parameter_id?: string
          sex?: Database["public"]["Enums"]["lab_range_sex"]
          text_normal?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "lab_reference_ranges_parameter_id_fkey"
            columns: ["parameter_id"]
            isOneToOne: false
            referencedRelation: "lab_test_parameters"
            referencedColumns: ["id"]
          },
        ]
      }
      lab_results: {
        Row: {
          amended_reason: string | null
          entered_at: string
          entered_by: string | null
          flag: Database["public"]["Enums"]["lab_flag"] | null
          id: string
          is_current: boolean
          order_item_id: string
          parameter_code: string
          parameter_id: string
          parameter_name: string
          range_label: string | null
          ref_critical_high: number | null
          ref_critical_low: number | null
          ref_high: number | null
          ref_low: number | null
          ref_text_normal: string | null
          sort_order: number
          unit: string | null
          value_numeric: number | null
          value_text: string | null
          value_type: Database["public"]["Enums"]["lab_value_type"]
          version: number
        }
        Insert: {
          amended_reason?: string | null
          entered_at?: string
          entered_by?: string | null
          flag?: Database["public"]["Enums"]["lab_flag"] | null
          id?: string
          is_current?: boolean
          order_item_id: string
          parameter_code: string
          parameter_id: string
          parameter_name: string
          range_label?: string | null
          ref_critical_high?: number | null
          ref_critical_low?: number | null
          ref_high?: number | null
          ref_low?: number | null
          ref_text_normal?: string | null
          sort_order?: number
          unit?: string | null
          value_numeric?: number | null
          value_text?: string | null
          value_type: Database["public"]["Enums"]["lab_value_type"]
          version?: number
        }
        Update: {
          amended_reason?: string | null
          entered_at?: string
          entered_by?: string | null
          flag?: Database["public"]["Enums"]["lab_flag"] | null
          id?: string
          is_current?: boolean
          order_item_id?: string
          parameter_code?: string
          parameter_id?: string
          parameter_name?: string
          range_label?: string | null
          ref_critical_high?: number | null
          ref_critical_low?: number | null
          ref_high?: number | null
          ref_low?: number | null
          ref_text_normal?: string | null
          sort_order?: number
          unit?: string | null
          value_numeric?: number | null
          value_text?: string | null
          value_type?: Database["public"]["Enums"]["lab_value_type"]
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: "lab_results_entered_by_fkey"
            columns: ["entered_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lab_results_order_item_id_fkey"
            columns: ["order_item_id"]
            isOneToOne: false
            referencedRelation: "lab_order_items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lab_results_parameter_id_fkey"
            columns: ["parameter_id"]
            isOneToOne: false
            referencedRelation: "lab_test_parameters"
            referencedColumns: ["id"]
          },
        ]
      }
      lab_samples: {
        Row: {
          clinic_id: string
          collected_at: string
          collected_by: string | null
          container: string | null
          id: string
          order_id: string
          rejected_at: string | null
          rejected_by: string | null
          rejected_reason: string | null
          sample_code: string
          sample_type: Database["public"]["Enums"]["lab_sample_type"]
        }
        Insert: {
          clinic_id: string
          collected_at?: string
          collected_by?: string | null
          container?: string | null
          id?: string
          order_id: string
          rejected_at?: string | null
          rejected_by?: string | null
          rejected_reason?: string | null
          sample_code: string
          sample_type: Database["public"]["Enums"]["lab_sample_type"]
        }
        Update: {
          clinic_id?: string
          collected_at?: string
          collected_by?: string | null
          container?: string | null
          id?: string
          order_id?: string
          rejected_at?: string | null
          rejected_by?: string | null
          rejected_reason?: string | null
          sample_code?: string
          sample_type?: Database["public"]["Enums"]["lab_sample_type"]
        }
        Relationships: [
          {
            foreignKeyName: "lab_samples_clinic_id_fkey"
            columns: ["clinic_id"]
            isOneToOne: false
            referencedRelation: "clinics"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lab_samples_collected_by_fkey"
            columns: ["collected_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lab_samples_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "lab_orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lab_samples_rejected_by_fkey"
            columns: ["rejected_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      lab_test_parameters: {
        Row: {
          choices: string[]
          code: string
          created_at: string
          decimals: number
          delta_percent: number | null
          id: string
          is_active: boolean
          name: string
          sort_order: number
          test_id: string
          unit: string | null
          updated_at: string
          value_type: Database["public"]["Enums"]["lab_value_type"]
        }
        Insert: {
          choices?: string[]
          code: string
          created_at?: string
          decimals?: number
          delta_percent?: number | null
          id?: string
          is_active?: boolean
          name: string
          sort_order?: number
          test_id: string
          unit?: string | null
          updated_at?: string
          value_type?: Database["public"]["Enums"]["lab_value_type"]
        }
        Update: {
          choices?: string[]
          code?: string
          created_at?: string
          decimals?: number
          delta_percent?: number | null
          id?: string
          is_active?: boolean
          name?: string
          sort_order?: number
          test_id?: string
          unit?: string | null
          updated_at?: string
          value_type?: Database["public"]["Enums"]["lab_value_type"]
        }
        Relationships: [
          {
            foreignKeyName: "lab_test_parameters_test_id_fkey"
            columns: ["test_id"]
            isOneToOne: false
            referencedRelation: "lab_tests"
            referencedColumns: ["id"]
          },
        ]
      }
      lab_tests: {
        Row: {
          category: Database["public"]["Enums"]["lab_category"]
          clinic_id: string
          code: string
          container: string | null
          created_at: string
          id: string
          is_active: boolean
          is_panel: boolean
          name: string
          sample_type: Database["public"]["Enums"]["lab_sample_type"]
          sort_order: number
          turnaround_hours: number
          updated_at: string
        }
        Insert: {
          category: Database["public"]["Enums"]["lab_category"]
          clinic_id: string
          code: string
          container?: string | null
          created_at?: string
          id?: string
          is_active?: boolean
          is_panel?: boolean
          name: string
          sample_type: Database["public"]["Enums"]["lab_sample_type"]
          sort_order?: number
          turnaround_hours?: number
          updated_at?: string
        }
        Update: {
          category?: Database["public"]["Enums"]["lab_category"]
          clinic_id?: string
          code?: string
          container?: string | null
          created_at?: string
          id?: string
          is_active?: boolean
          is_panel?: boolean
          name?: string
          sample_type?: Database["public"]["Enums"]["lab_sample_type"]
          sort_order?: number
          turnaround_hours?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "lab_tests_clinic_id_fkey"
            columns: ["clinic_id"]
            isOneToOne: false
            referencedRelation: "clinics"
            referencedColumns: ["id"]
          },
        ]
      }
      patient_chat_messages: {
        Row: {
          citations: Json
          clinic_id: string
          content: string
          created_at: string
          error_code: string | null
          id: string
          input_tokens: number | null
          latency_ms: number | null
          model: string | null
          output_tokens: number | null
          role: Database["public"]["Enums"]["chat_role"]
          session_id: string
        }
        Insert: {
          citations?: Json
          clinic_id: string
          content: string
          created_at?: string
          error_code?: string | null
          id?: string
          input_tokens?: number | null
          latency_ms?: number | null
          model?: string | null
          output_tokens?: number | null
          role: Database["public"]["Enums"]["chat_role"]
          session_id: string
        }
        Update: {
          citations?: Json
          clinic_id?: string
          content?: string
          created_at?: string
          error_code?: string | null
          id?: string
          input_tokens?: number | null
          latency_ms?: number | null
          model?: string | null
          output_tokens?: number | null
          role?: Database["public"]["Enums"]["chat_role"]
          session_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "patient_chat_messages_clinic_id_fkey"
            columns: ["clinic_id"]
            isOneToOne: false
            referencedRelation: "clinics"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "patient_chat_messages_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "patient_chat_sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      patient_chat_sessions: {
        Row: {
          clinic_id: string
          created_at: string
          doctor_id: string | null
          id: string
          patient_id: string
          title: string
          updated_at: string
          user_id: string
        }
        Insert: {
          clinic_id: string
          created_at?: string
          doctor_id?: string | null
          id?: string
          patient_id: string
          title: string
          updated_at?: string
          user_id: string
        }
        Update: {
          clinic_id?: string
          created_at?: string
          doctor_id?: string | null
          id?: string
          patient_id?: string
          title?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "patient_chat_sessions_clinic_id_fkey"
            columns: ["clinic_id"]
            isOneToOne: false
            referencedRelation: "clinics"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "patient_chat_sessions_doctor_id_fkey"
            columns: ["doctor_id"]
            isOneToOne: false
            referencedRelation: "doctors"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "patient_chat_sessions_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: false
            referencedRelation: "patients"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "patient_chat_sessions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      patient_medical_profiles: {
        Row: {
          allergies: string[]
          blood_group: string | null
          chronic_conditions: string[]
          clinic_id: string
          created_at: string
          patient_id: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          allergies?: string[]
          blood_group?: string | null
          chronic_conditions?: string[]
          clinic_id: string
          created_at?: string
          patient_id: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          allergies?: string[]
          blood_group?: string | null
          chronic_conditions?: string[]
          clinic_id?: string
          created_at?: string
          patient_id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "patient_medical_profiles_clinic_id_fkey"
            columns: ["clinic_id"]
            isOneToOne: false
            referencedRelation: "clinics"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "patient_medical_profiles_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: true
            referencedRelation: "patients"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "patient_medical_profiles_updated_by_fkey"
            columns: ["updated_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      patient_record_access_log: {
        Row: {
          action: Database["public"]["Enums"]["record_access_action"]
          appointment_id: string | null
          clinic_id: string
          created_at: string
          id: number
          patient_id: string
          report_id: string | null
          session_id: string | null
          user_id: string | null
        }
        Insert: {
          action: Database["public"]["Enums"]["record_access_action"]
          appointment_id?: string | null
          clinic_id: string
          created_at?: string
          id?: never
          patient_id: string
          report_id?: string | null
          session_id?: string | null
          user_id?: string | null
        }
        Update: {
          action?: Database["public"]["Enums"]["record_access_action"]
          appointment_id?: string | null
          clinic_id?: string
          created_at?: string
          id?: never
          patient_id?: string
          report_id?: string | null
          session_id?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "patient_record_access_log_appointment_id_fkey"
            columns: ["appointment_id"]
            isOneToOne: false
            referencedRelation: "appointments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "patient_record_access_log_clinic_id_fkey"
            columns: ["clinic_id"]
            isOneToOne: false
            referencedRelation: "clinics"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "patient_record_access_log_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: false
            referencedRelation: "patients"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "patient_record_access_log_report_id_fkey"
            columns: ["report_id"]
            isOneToOne: false
            referencedRelation: "patient_reports"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "patient_record_access_log_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "patient_chat_sessions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "patient_record_access_log_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      patient_record_chunks: {
        Row: {
          chunk_index: number
          clinic_id: string
          content: string
          content_hash: string
          content_tsv: unknown
          created_at: string
          embedding: string
          embedding_model: string
          id: string
          metadata: Json
          patient_id: string
          source_date: string | null
          source_id: string
          source_type: Database["public"]["Enums"]["record_source_type"]
        }
        Insert: {
          chunk_index: number
          clinic_id: string
          content: string
          content_hash: string
          content_tsv?: unknown
          created_at?: string
          embedding: string
          embedding_model: string
          id?: string
          metadata?: Json
          patient_id: string
          source_date?: string | null
          source_id: string
          source_type: Database["public"]["Enums"]["record_source_type"]
        }
        Update: {
          chunk_index?: number
          clinic_id?: string
          content?: string
          content_hash?: string
          content_tsv?: unknown
          created_at?: string
          embedding?: string
          embedding_model?: string
          id?: string
          metadata?: Json
          patient_id?: string
          source_date?: string | null
          source_id?: string
          source_type?: Database["public"]["Enums"]["record_source_type"]
        }
        Relationships: [
          {
            foreignKeyName: "patient_record_chunks_clinic_id_fkey"
            columns: ["clinic_id"]
            isOneToOne: false
            referencedRelation: "clinics"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "patient_record_chunks_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: false
            referencedRelation: "patients"
            referencedColumns: ["id"]
          },
        ]
      }
      patient_reports: {
        Row: {
          clinic_id: string
          consultation_id: string | null
          created_at: string
          extracted_text: string | null
          extraction_method:
            | Database["public"]["Enums"]["extraction_method"]
            | null
          id: string
          ingestion_error: string | null
          ingestion_status: Database["public"]["Enums"]["ingestion_status"]
          is_generated: boolean
          lab_order_id: string | null
          mime_type: string
          page_count: number | null
          patient_id: string
          report_date: string | null
          report_type: Database["public"]["Enums"]["report_type"]
          size_bytes: number
          storage_path: string
          title: string
          updated_at: string
          uploaded_by: string | null
        }
        Insert: {
          clinic_id: string
          consultation_id?: string | null
          created_at?: string
          extracted_text?: string | null
          extraction_method?:
            | Database["public"]["Enums"]["extraction_method"]
            | null
          id?: string
          ingestion_error?: string | null
          ingestion_status?: Database["public"]["Enums"]["ingestion_status"]
          is_generated?: boolean
          lab_order_id?: string | null
          mime_type: string
          page_count?: number | null
          patient_id: string
          report_date?: string | null
          report_type: Database["public"]["Enums"]["report_type"]
          size_bytes: number
          storage_path: string
          title: string
          updated_at?: string
          uploaded_by?: string | null
        }
        Update: {
          clinic_id?: string
          consultation_id?: string | null
          created_at?: string
          extracted_text?: string | null
          extraction_method?:
            | Database["public"]["Enums"]["extraction_method"]
            | null
          id?: string
          ingestion_error?: string | null
          ingestion_status?: Database["public"]["Enums"]["ingestion_status"]
          is_generated?: boolean
          lab_order_id?: string | null
          mime_type?: string
          page_count?: number | null
          patient_id?: string
          report_date?: string | null
          report_type?: Database["public"]["Enums"]["report_type"]
          size_bytes?: number
          storage_path?: string
          title?: string
          updated_at?: string
          uploaded_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "patient_reports_clinic_id_fkey"
            columns: ["clinic_id"]
            isOneToOne: false
            referencedRelation: "clinics"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "patient_reports_consultation_id_fkey"
            columns: ["consultation_id"]
            isOneToOne: false
            referencedRelation: "consultations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "patient_reports_lab_order_id_fkey"
            columns: ["lab_order_id"]
            isOneToOne: false
            referencedRelation: "lab_orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "patient_reports_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: false
            referencedRelation: "patients"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "patient_reports_uploaded_by_fkey"
            columns: ["uploaded_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      patients: {
        Row: {
          address: string | null
          age_years: number | null
          alternate_phone: string | null
          clinic_id: string
          created_at: string
          created_by: string | null
          date_of_birth: string | null
          full_name: string
          gender: Database["public"]["Enums"]["gender"] | null
          id: string
          notes: string | null
          phone: string
          updated_at: string
        }
        Insert: {
          address?: string | null
          age_years?: number | null
          alternate_phone?: string | null
          clinic_id: string
          created_at?: string
          created_by?: string | null
          date_of_birth?: string | null
          full_name: string
          gender?: Database["public"]["Enums"]["gender"] | null
          id?: string
          notes?: string | null
          phone: string
          updated_at?: string
        }
        Update: {
          address?: string | null
          age_years?: number | null
          alternate_phone?: string | null
          clinic_id?: string
          created_at?: string
          created_by?: string | null
          date_of_birth?: string | null
          full_name?: string
          gender?: Database["public"]["Enums"]["gender"] | null
          id?: string
          notes?: string | null
          phone?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "patients_clinic_id_fkey"
            columns: ["clinic_id"]
            isOneToOne: false
            referencedRelation: "clinics"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "patients_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      prescription_items: {
        Row: {
          created_at: string
          dosage_form: string | null
          dose: string | null
          duration_days: number | null
          frequency: string | null
          id: string
          instructions: string | null
          medicine_name: string
          prescription_id: string
          route: string | null
          sort_order: number
          strength: string | null
          timing: string | null
        }
        Insert: {
          created_at?: string
          dosage_form?: string | null
          dose?: string | null
          duration_days?: number | null
          frequency?: string | null
          id?: string
          instructions?: string | null
          medicine_name: string
          prescription_id: string
          route?: string | null
          sort_order?: number
          strength?: string | null
          timing?: string | null
        }
        Update: {
          created_at?: string
          dosage_form?: string | null
          dose?: string | null
          duration_days?: number | null
          frequency?: string | null
          id?: string
          instructions?: string | null
          medicine_name?: string
          prescription_id?: string
          route?: string | null
          sort_order?: number
          strength?: string | null
          timing?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "prescription_items_prescription_id_fkey"
            columns: ["prescription_id"]
            isOneToOne: false
            referencedRelation: "prescriptions"
            referencedColumns: ["id"]
          },
        ]
      }
      prescriptions: {
        Row: {
          clinic_id: string
          consultation_id: string
          created_at: string
          id: string
          patient_id: string
          updated_at: string
        }
        Insert: {
          clinic_id: string
          consultation_id: string
          created_at?: string
          id?: string
          patient_id: string
          updated_at?: string
        }
        Update: {
          clinic_id?: string
          consultation_id?: string
          created_at?: string
          id?: string
          patient_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "prescriptions_clinic_id_fkey"
            columns: ["clinic_id"]
            isOneToOne: false
            referencedRelation: "clinics"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "prescriptions_consultation_id_fkey"
            columns: ["consultation_id"]
            isOneToOne: true
            referencedRelation: "consultations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "prescriptions_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: false
            referencedRelation: "patients"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          clinic_id: string
          created_at: string
          full_name: string
          id: string
          is_active: boolean
          phone: string | null
          role: Database["public"]["Enums"]["user_role"]
        }
        Insert: {
          clinic_id: string
          created_at?: string
          full_name: string
          id: string
          is_active?: boolean
          phone?: string | null
          role: Database["public"]["Enums"]["user_role"]
        }
        Update: {
          clinic_id?: string
          created_at?: string
          full_name?: string
          id?: string
          is_active?: boolean
          phone?: string | null
          role?: Database["public"]["Enums"]["user_role"]
        }
        Relationships: [
          {
            foreignKeyName: "profiles_clinic_id_fkey"
            columns: ["clinic_id"]
            isOneToOne: false
            referencedRelation: "clinics"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      actor_type: "user" | "system"
      appointment_source: "walk_in" | "phone" | "manual" | "whatsapp" | "voice"
      appointment_status:
        | "pending_confirmation"
        | "scheduled"
        | "checked_in"
        | "in_consultation"
        | "completed"
        | "cancelled"
        | "no_show"
      chat_role: "user" | "assistant"
      consultation_status: "draft" | "finalized"
      extraction_method: "text"
      gender: "male" | "female" | "other"
      inbound_channel: "whatsapp" | "voice"
      inbound_status: "received" | "auto_booked" | "needs_review" | "rejected"
      ingestion_status:
        | "pending"
        | "processing"
        | "indexed"
        | "failed"
        | "no_text"
      job_status: "pending" | "processing" | "done" | "failed"
      lab_category:
        | "haematology"
        | "biochemistry"
        | "hormones"
        | "urine"
        | "serology"
        | "other"
      lab_flag:
        | "normal"
        | "low"
        | "high"
        | "critical_low"
        | "critical_high"
        | "abnormal"
      lab_item_status:
        | "ordered"
        | "sample_collected"
        | "sample_rejected"
        | "result_entered"
        | "verified"
        | "released"
        | "cancelled"
      lab_order_status:
        | "ordered"
        | "in_progress"
        | "partially_released"
        | "released"
        | "cancelled"
      lab_priority: "routine" | "urgent" | "stat"
      lab_range_sex: "male" | "female" | "any"
      lab_sample_type: "blood" | "urine" | "stool" | "swab" | "other"
      lab_value_type: "numeric" | "text" | "choice"
      record_access_action:
        | "chart_open"
        | "chat_question"
        | "report_view"
        | "report_upload"
      record_source_type: "profile" | "consultation" | "report" | "lab_result"
      report_type:
        | "lab"
        | "imaging"
        | "discharge_summary"
        | "referral"
        | "old_prescription"
        | "other"
      user_role:
        | "admin"
        | "receptionist"
        | "doctor"
        | "lab_technician"
        | "lab_supervisor"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      actor_type: ["user", "system"],
      appointment_source: ["walk_in", "phone", "manual", "whatsapp", "voice"],
      appointment_status: [
        "pending_confirmation",
        "scheduled",
        "checked_in",
        "in_consultation",
        "completed",
        "cancelled",
        "no_show",
      ],
      chat_role: ["user", "assistant"],
      consultation_status: ["draft", "finalized"],
      extraction_method: ["text"],
      gender: ["male", "female", "other"],
      inbound_channel: ["whatsapp", "voice"],
      inbound_status: ["received", "auto_booked", "needs_review", "rejected"],
      ingestion_status: [
        "pending",
        "processing",
        "indexed",
        "failed",
        "no_text",
      ],
      job_status: ["pending", "processing", "done", "failed"],
      lab_category: [
        "haematology",
        "biochemistry",
        "hormones",
        "urine",
        "serology",
        "other",
      ],
      lab_flag: [
        "normal",
        "low",
        "high",
        "critical_low",
        "critical_high",
        "abnormal",
      ],
      lab_item_status: [
        "ordered",
        "sample_collected",
        "sample_rejected",
        "result_entered",
        "verified",
        "released",
        "cancelled",
      ],
      lab_order_status: [
        "ordered",
        "in_progress",
        "partially_released",
        "released",
        "cancelled",
      ],
      lab_priority: ["routine", "urgent", "stat"],
      lab_range_sex: ["male", "female", "any"],
      lab_sample_type: ["blood", "urine", "stool", "swab", "other"],
      lab_value_type: ["numeric", "text", "choice"],
      record_access_action: [
        "chart_open",
        "chat_question",
        "report_view",
        "report_upload",
      ],
      record_source_type: ["profile", "consultation", "report", "lab_result"],
      report_type: [
        "lab",
        "imaging",
        "discharge_summary",
        "referral",
        "old_prescription",
        "other",
      ],
      user_role: [
        "admin",
        "receptionist",
        "doctor",
        "lab_technician",
        "lab_supervisor",
      ],
    },
  },
} as const
